databases:
  - name: postgres
    ipAllowList: []
    databaseName: doc_share_db
    user: doc_share_db_user

services:
  - type: web
    name: doc_share
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
